### ISSUE TITLE
TypeScript error for package

### ISSUE THREAD

**Issue by rumfiske** [i18nexus/next-i18n-router#1]
![Code_vtCnsxdWk7](https://github.com/i18nexus/next-i18n-router/assets/59709554/799d5888-aa65-4568-8a92-5d41f4915a54)

Can we get this working with typescript? :)

**Comment by i18nexus** [comment]
@rumfiske TypeScript support coming soon! It should be available by next week. We will update this issue when it's released.

**Comment by i18nexus** [comment]
Typescript support released with v2.0.0 🎉
