### ISSUE TITLE
Rewrite drops every URL Query

### ISSUE THREAD

**Issue by Otisz** [i18nexus/next-i18n-router#13]
Hello!

Maybe I missed something in the documentation, but it thinks next-i18n-router drops every URL query by default after rewrite.

## The problem

Jane is using the app in english (default) and sends the following link: `https://example.com/path?query=something&page=2`

John is using the app in german and opens the link and it redirect him to `https://example.com/de/path`

## Expected behavior

John is getting redirected to `https://example.com/de/path?query=something&page=2`

---

*I hope my silly example makes it easier to understand my issue.*

**Comment by i18nexus** [comment]
Interesting, thanks for bringing this up! We'll take a look and get back to you soon.

**Comment by Otisz** [comment]
This only occours when a non-default language user opens a default language link: \
`en` -> `de` drops all the queries.

In the other way, when the default language user opens the non-default language link: \
`de` -> `en` no rewrite to the default language, hence keeps all the queries

**Comment by i18nexus** [comment]
Thanks again for the report! This has now been fixed in v3.2.0
