### ISSUE TITLE
example of usage with react intl next 13

### ISSUE THREAD

**Issue by zakidze** [i18nexus/next-i18n-router#14]
can you please provide a full example in this repo with next 13  server component and client component with react intl included

**Comment by i18nexus** [comment]
The steps to implement next-i18n-router with Next 13 for both Server and Client Components with react-intl are available in the README. But it would be useful to have a full project example in this repo. Thanks for the feedback. We will add an example soon.

**Comment by revengemiroz** [comment]
can you give example code the read me is not clear on how to use

**Comment by i18nexus** [comment]
@revengemiroz We will have full example projects in this repo soon. In the meantime, you can read our full walkthrough here: https://i18nexus.com/tutorials/nextjs/react-intl

**Comment by i18nexus** [comment]
A react-intl example has been added to the repo:
https://github.com/i18nexus/next-i18n-router/tree/main/examples/react-intl-example

**Comment by zakidze** [comment]
thank uuuuu

**Comment by zakidze** [comment]
i want to ask if i have alot of translations , 
like in about page 
index page
contact page,


will contact page translations get loaded in index page???  (for perfomance reasons i dont need contact tags in index page)
are the translations static ? they get loaded at build time?

**Comment by revengemiroz** [comment]
yes

> i want to ask if i have alot of translations , like in about page index page contact page,
> 
> will contact page translations get loaded in index page??? (for perfomance reasons i dont need contact tags in index page) are the translations static ? they get loaded at build time?

yes

**Comment by i18nexus** [comment]
@zakidze @revengemiroz

> will contact page translations get loaded in index page???

If you are following the basic example in the README, then yes all your translations will be loaded for all pages. You likely will want to load only the translations required for each page. You can do this by namespacing your JSON files. You just need to change your `getIntl` function take a namespace as an argument and only load the necessary JSON file.

We do have a tutorial on our website that implements it this way:
https://i18nexus.com/tutorials/nextjs/react-intl

> do they get loaded at build time?

Currently only your defaultLocale pages will be generated at build time. Other languages will generate at request time.

But we have good news about this 🙂 In version 4.0.0, we are adding a config option to use a dynamic segment for the locale in the pathname to solve this exact problem. So pages for all locales can be generated at build time. Expect this release by the end of the week. It won't require any major code changes.

**Comment by zakidze** [comment]
thats greate news  
so if all tags get generated at build time it wont matter if you file split witch is super great

however i saw you use 'use client' in the ServerIntlProvider.tsx  file and you wrapped your page with that, 
does it mean that all translated page will be client????


also if we use a getseerver side props , mean fetch with no cache will it conflict

**Comment by i18nexus** [comment]
@zakidze Nope 🙂 It will still be a Server Component and rendered on the Server. The provider just provides to all nested Client Components. It does not affect child Server Component logic.

**Comment by zakidze** [comment]
happy to hear that  hope for you guys the best 
i be waiting for the next realease
