### ISSUE TITLE
`currentLocale()` returns `null`

### ISSUE THREAD

**Issue by sshmaxime** [i18nexus/next-i18n-router#17]
Hello, I'm currently trying to set up a project with your package but I keep getting `null` from my Server components. That being said, it works well on Client components. Did you miss something in the doc ? I'm using Next `13.4.10`

**Comment by i18nexus** [comment]
Hmm, it should never return `null`. We can't seem to reproduce this. Are you able to provide a minimal reproducible example?

**Comment by revengemiroz** [comment]
same issue and how do i change the locale language

**Comment by i18nexus** [comment]
@revengemiroz Please see #15 to see for an example of changing languages.

Can you provide a reproducible repo for ‘currentLocale’ returning ‘null’?

**Comment by i18nexus** [comment]
@sshmaxime @revengemiroz Are either of you able to send some code that reproduces this issue?

**Comment by talebkhah** [comment]
@sshmaxime  @revengemiroz 

if you have a src folder, the middleware file must be inside it.
Otherwise, the middleware must be at the same level as pages or app folder.

**Comment by i18nexus** [comment]
Thanks @talebkhah! I assume this is the problem they were having. I'm going to close this issue.
