### ISSUE TITLE
Support linguijs

### ISSUE THREAD

**Issue by Jcaster99** [i18nexus/next-i18n-router#20]
Is best if this can support https://lingui.dev/
Thanks author.

**Comment by i18nexus** [comment]
I'm not sure I understand. Is there an issue you're running into specifically when trying to use lingui?

This library is agnostic to what i18n library you use. It doesn't matter if you want to use react-intl, lingui, i18next, etc... The next-i18n-router library simply provides internationalized routing. Nothing more. If lingui.js works in Next.js, then you can certainly use it with this library.

I know right now we only have an example for react-intl integration, but we will be adding more examples for other i18n libraries in the near future! We also welcome anyone to make a PR into our `examples` folder with other library integrations.

**Comment by i18nexus** [comment]
Going to close this one since all i18n libraries are inherently supported.
