### ISSUE TITLE
Problem with non-default language and not changing url when clicking on a button

### ISSUE THREAD

**Issue by shahryarjb** [i18nexus/next-i18n-router#21]
Hello, I am using `"next-i18n-router": "^4.0.0",`. when I click or use `useRouter from 'next/navigation'` in app router next, in non-default language my url is going to change `fa` as default but `currentLocale()` returns `en`

### I create a short videos for this problem:

https://github.com/i18nexus/next-i18n-router/assets/8413604/e90e7cbb-8387-4a18-87ef-f243a8869e98

As you see I was in `en` url and click to a `Link` and it was changed to default language which is `fa`

## my config
```javascript
const i18nConfig = {
  locales: ['en', 'fa'],
  defaultLocale: 'fa',
  localeDetector: false,
  prefixDefault: true,
  localeCookie: 'NEXT_LOCALE',
};
module.exports = i18nConfig;
```

## My middleware
```javascript
import { i18nRouter } from 'next-i18n-router';
import i18nConfig from './i18nConfig';

export function middleware(request) {
  return i18nRouter(request, i18nConfig);
}

export const config = {
  matcher: '/((?!api|static|.*\\..*|_next).*)'
};
```

## Server side:
```javascript
import { currentLocale } from 'next-i18n-router';
import { getDictionary } from './[lang]/dictionaries';

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const locale = currentLocale();
  const dict = await getDictionary(locale as 'fa' | 'en');
  const session = await getServerSession(authOptions);

...
```

### My dir
![Screenshot 2023-09-27 at 16 30 31](https://github.com/i18nexus/next-i18n-router/assets/8413604/8e1a7f8f-d5b5-43b3-b22d-bc942803bbf2)

Ho can fix it? it should be noted when I push programmatically, it just goes to default language not current language

Thank you in advanced

**Comment by i18nexus** [comment]
Hi! This is actually working as designed. When you link to `/auth/login` without a locale in the path, the middleware is detecting that your browser's preferred locale is `fa`. So it is redirecting you to `fa`.

There are 2 options for handling this:

1) Set the `NEXT_LOCALE` cookie to override the `localeDetector` logic.
2) Prefix the `href`s in your Links with the current locale. For example:
```
<Link href={`/${currentLocale}/auth/login`}>
```

In a real-world scenario, a user would prefer to be redirected to their own language when visiting a link at the base path. If they want to change their language, you should provide a dropdown to select a language and then set `NEXT_LOCALE` with their selection. Manually typing the URL in the browser for another language will not automatically set the cookie for that language.

**Comment by shahryarjb** [comment]
Thank you @i18nexus , could you please give me `NEXT_LOCALE` example please? I could not be able to find any example for setting this and a button to change the cookie
Thanks

**Comment by i18nexus** [comment]
Sure, you can see an example in #15 

I'm going to close this issue, but still let me know if you have any questions.
