### ISSUE TITLE
The default error page at the first level of nesting.

### ISSUE THREAD

**Issue by oskolsky** [i18nexus/next-i18n-router#24]
Thank you for the quick response to the previous bug.

I would also like to mention another atypical behavior. I'm not sure if it's a bug, but with my application structure, when attempting to access a non-existent URL in the first level of nesting, it redirects me to the default 404 page instead of my custom one.

<img width="206" alt="Screenshot 2023-10-02 at 02 40 08" src="https://github.com/i18nexus/next-i18n-router/assets/1423686/f6333813-df43-4571-842d-7e95e120a001">

For example:

**http://localhost:3000/places/1000 - show my custom error page**
<img width="1305" alt="Screenshot 2023-10-02 at 22 28 47" src="https://github.com/i18nexus/next-i18n-router/assets/1423686/6587eb49-e3b7-4d04-82f0-15d0d68160b9">

**http://localhost:3000/adad - show Nextjs default error page**
<img width="927" alt="Screenshot 2023-10-02 at 22 28 43" src="https://github.com/i18nexus/next-i18n-router/assets/1423686/0cf168b5-b7d4-4df1-94ac-341bd458db29">

Of course, I can fix this by moving **layout.tsx**, **not-found.tsx**, and **error.tsx** to the root of the app directory, outside of [locale]. However, in that case, I won't be able to use localizations in these components.

**Comment by i18nexus** [comment]
Thanks for pointing this out. After a little research this unfortunately appears to be an issue in Next.js:

https://github.com/vercel/next.js/discussions/50034#discussion-5211681

You can find a workaround in the above discussion. Essentially it requires you to use a catch-all dynamic segment that renders a dummy component that calls `notFound`.

This answer on Stackoverflow also describes the same problem and solution: https://stackoverflow.com/a/75625136/7629239

**Comment by oskolsky** [comment]
ok, thank you
