### ISSUE TITLE
localeDetector issue

### ISSUE THREAD

**Issue by robinsingh-bw** [i18nexus/next-i18n-router#26]
Hi,

localeDetector returns default locale when no accept-language header provided. It would be better to determine locale from the path first. Atm this is resulting in the default english homepage content being shown when user is visiting a path like /de/some-other-page.

https://github.com/i18nexus/next-i18n-router/commit/a009bb40a26d95d6445f288bf0cd42fc6d6512f4#diff-3ff8b369767547151a5d25ae0e2e05037d86a53ddeea3be8f1d98ee340296bffR16

**Comment by i18nexus** [comment]
`localeDetector` doesn't run at all if a locale is in the path. It is only called when there is no locale in the path.

Can you provide steps to reproduce? I've tried running a request to `/de/some-other-page` with no accept-language header and it seems to work as expected.

**Comment by robinsingh-bw** [comment]
Sorry, my bad. I saw the new changes and thought it must be related to that without digging deeper. I am sharing the below info for now but can try to create a project with a reproduction of the problem later.

Folder structure:
`
/app/[slug]/page.js
/app/test-page/page.js
/app/page.js
`

`
const nextConfig = {
  trailingSlash: true,
}
`

next-i18n-router: 4.1.2

**Problem:**
When the app is deployed to vercel and I visit `/de/test-page/` directly (through address bar) then `/app/page.js` gets rendered instead of `/app/test-page/page.js`. The url in the address bar is still `/de/test-page/`. The locale is being set correctly (i.e. I see German on `/app/page.js`). If I then click on an internal link on the homepage to the test-page, the content gets rendered correctly (url is still same).

This issue only happens on vercel, both local dev and build work correctly.

I downgraded to next-i18n-router 3.2.0 and the issue disappeared but this version has other locale issues so its not usable in prod (for ex. the accept-lang issue that was fixed in 4.1.2).

**Comment by robinsingh-bw** [comment]
Works with 3.3.0, breaks with 4.0.0

**Comment by i18nexus** [comment]
Interesting. Thanks for the feedback. We’ll have to try the latest version on Vercel.

In the meantime, can you provide your i18n config?

Also can you test if you get this issue without trailing slash?

Can you also try using the “dynamicSegment” routingStrategy and see if that works?

We’ll test further on Vercel as soon as we can!

**Comment by robinsingh-bw** [comment]
I actually just tested with dynamicSegment and its working as expected now (even on vercel). I think we will stick with this solution as its also closer to how nextjs wants apps to be built, will test some edge cases later on and report back if any issues

**Comment by i18nexus** [comment]
Cool, thanks for trying that. Using `"dynamicSegment"` also allows you to use `generateStaticProps` which is better for production environments anyway, so I'd recommend that. In the next major version of this library we're likely going to make it the default `routingStrategy`. (Perhaps get rid of the rewrite strategy altogether... still discussing).

Anyway, it sounds like there's a potential issue with rewrites when deployed to Vercel. I'll report back here after further investigation.

**Comment by i18nexus** [comment]
**Update**: We've decided that we will only be supporting the `"dynamicSegment"` routing strategy in version 5.0.0 for the reasons found above. We will therefore be removing the `routingStrategy` config option since it's no longer needed. Expect this to be released by the end of the week.

**Comment by i18nexus** [comment]
The rewrite routing strategy has been removed in v5.0.0
