### ISSUE TITLE
Basepath support is not intuitive

### ISSUE THREAD

**Issue by paulvanbrenk** [i18nexus/next-i18n-router#3]
Basepath support is not intuitive.

If you add a basepath to the `next.config.js` navigation to subpages is not consistent (or untuitive).

Add a basepath `home` and a route `documents`. Then the following navigation is not intuitive when `prefixDefault` is set to `true`

e.g. `http://localhost:3000/home/document` redirects to `http://localhost:3000/en/document`.

Further I expected `http://localhost:3000/home/` to be rewritten to `http://localhost:3000/home/en`.

This limitation means it probably doesn't work with rewrites to another domain, which we use to host several nextjs apps under the same domain.

(see: https://nextjs.org/docs/pages/api-reference/next-config-js/rewrites#rewriting-to-an-external-url)

**Comment by i18nexus** [comment]
Thanks for bringing this to our attention! Currently the `i18nRouter` does not support handling `basePath`. We already have a patch in place and currently undergoing testing. Expect this patch to be included in version 3.2 next week.

**Comment by i18nexus** [comment]
`basePath` is now supported in v3.1.0
