### ISSUE TITLE
localeDetector async - by ip address

### ISSUE THREAD

**Issue by luluhoc** [i18nexus/next-i18n-router#34]
Hello, 

I have an endpoint that checks with MaxMind DB the location of the IP but it seems that localeDetector doesn't accept async functions how can I achieve it?

```
const fetchIpData = async (): Promise<{
  error: boolean
  country_code: string | null
  region: Region | null
}> => {
  const data = await medusaRequest("GET", "/ip-lookup")

  return data.body
}
```

**Comment by i18nexus** [comment]
Thanks for the feedback. We're currently looking into implementing this and will get back to you soon.

**Comment by i18nexus** [comment]
Unfortunately we're not going to be able to implement this without making the entire `i18nRouter` an async function which we want to avoid. However there is a simple workaround to do this right now:

```
export async function middleware(request) {
  const ipLocale = await fetchIpLocale();

  const config = {
    ...i18nConfig,
    localeDetector: () => ipLocale
  }

  return i18nRouter(request, config);
}
```

We will consider making i18nRouter an async function in a future major version, but at the moment it is not planned since the above workaround should suffice. Let us know if this works for you.

**Comment by luluhoc** [comment]
> Unfortunately we're not going to be able to implement this without making the entire `i18nRouter` an async function which we want to avoid. However there is a simple workaround to do this right now:
> 
> ```
> export async function middleware(request) {
>   const ipLocale = await fetchIpLocale();
> 
>   const config = {
>     ...i18nConfig,
>     localeDetector: () => ipLocale
>   }
> 
>   return i18nRouter(request, config);
> }
> ```
> 
> We will consider making i18nRouter an async function in a future major version, but at the moment it is not planned since the above workaround should suffice. Let us know if this works for you.

Yeah, it works for me thank you for all your hard work! I have tried 1000 tutorials and blog posts on how to make an app router localized and nothing worked until I found this repo! I was amazed at how easy to implement and out of the box it was working as intended. Thanks again!

**Comment by i18nexus** [comment]
Thanks for the feedback! Much appreciated
