### ISSUE TITLE
set up default launugage dynamcly

### ISSUE THREAD

**Issue by zakidze** [i18nexus/next-i18n-router#4]
i really liked the library after tedting it however how to set the default launguage from front end a launguage switcher, for example the default launguage of my website is english....i change it to german....i want next time i enter i find it in german  , this applies for server and client component,

**Comment by i18nexus** [comment]
To change the language, you should use the NEXT_LOCALE cookie as mentioned [https://github.com/i18nexus/next-i18n-router#locale-cookie-optional](here).

You can find an example language switcher component at the bottom of [this tutorial](https://i18nexus.com/tutorials/nextjs/react-intl).

Does this solve your issue?

**Comment by zakidze** [comment]
didnt test this yet but i m thinking about if it will work   with server component : hope it does

**Comment by i18nexus** [comment]
The cookie is read by the server. It will work in both server and client components. I’ll leave this issue open until you’re able to test, but we have tested it and it should work as expected.

**Comment by zakidze** [comment]
thank you you guys are tha best it  works fine and everything works + no need to wrap in [lang] transitoin between page is smooth + server and client component works and pages also works kudos guys
however i want to ask
how did you make the server read from client cookies befor sending the page to the client

**Comment by i18nexus** [comment]
No problem! The cookie is read in the `i18nRouter` function which receives the request in `middleware.js`. The cookie is ready by running `request.cookies.get('NEXT_LOCALE')`. You can read about it in the Next.js docs: https://nextjs.org/docs/app/api-reference/functions/next-request#getname
