### ISSUE TITLE
serverSetCookie does not set the cookie as expected

### ISSUE THREAD

**Issue by sirajtahra** [i18nexus/next-i18n-router#46]
Trying to set `serverSetCookie: "always"` does not add the cookie as expected based on the url

**Comment by i18nexus** [comment]
HI @sirajtahra. Please make sure you're on the latest version of this package. If you are, can you please provide your config?

**Comment by sirajtahra** [comment]
Version: 5..2.0

configuation:
```
const i18nConfig: Config = {
  locales: ["en-AE", "ar-AE"],
  defaultLocale: "en-AE",
  prefixDefault: true,
  serverSetCookie: 'always',
};
```

**Comment by i18nexus** [comment]
I'm not able to reproduce any issues with this. Can you tell me what you're experiencing? Can you provide a reproducible repo?

**Comment by sirajtahra** [comment]
Seems to be working now -it seems the package was still cached with turborepo this is why it wasnt working - Thank you
