### ISSUE TITLE
Nextjs v14.1 support

### ISSUE THREAD

**Issue by DaliborPan** [i18nexus/next-i18n-router#51]
Hello,

In my project, I have updated my Nextjs version to 14.1. However, due to [definition](https://github.com/i18nexus/next-i18n-router/blob/main/src/i18nRouter.ts#L6) of `i18nRouter` accepting `request: NextRequest`, which comes from Nextjs v14.0.4, it is not working anymore.

Do you plan to bump your Nextjs version? Thanks!

**Comment by i18nexus** [comment]
Thanks! Just released in v5.2.1... We'll get this automated

**Comment by DaliborPan** [comment]
Hey @i18nexus, thanks for the update, but I still can't get it working tho. 

Here you can see I have installed the latest version of the package:
![image](https://github.com/i18nexus/next-i18n-router/assets/72815195/1c95162d-50b4-44e7-81f2-07fc075bb737)

But `NextRequest` is being still imported from Nextjs v14.0.4.
![Screenshot 2024-02-01 at 17 58 33](https://github.com/i18nexus/next-i18n-router/assets/72815195/da24ee2b-e146-4f5d-b500-13a339368438)

Any idea? I have tried to delete node modules, remove package, add package again, still not working. Thanks.

**Comment by i18nexus** [comment]
Hmm, can you try deleting your node_modules as well as package.json and running npm install again?

Also run npm update on your react and react typings. If I recall correctly, I believe I had to update these on our example project.

**Comment by DaliborPan** [comment]
It looks like deleting `pnpm-lock.yaml` and then installing helped. Thanks!

**Comment by i18nexus** [comment]
Great!
