### ISSUE TITLE
not-found and error pages not working

### ISSUE THREAD

**Issue by VugarAhmadov** [i18nexus/next-i18n-router#52]
After updating to latest version of nextjs and next-i18n-router  my custom not found and error pages not working anymore
i checked the example with react-intl and not-found page not working there too

**Comment by VugarAhmadov** [comment]
found the workaround. created [...not-found/page.tsx inside [locale] folder and wrote this code

import { notFound } from "next/navigation";

export default function NotFoundCatchAll() {
  notFound();
}

hence, closing this issue

**Comment by i18nexus** [comment]
Yes, `not-found` pages have to be done this way in dynamic segments in Next 13+. More detail can be read here in this previous issue: https://github.com/i18nexus/next-i18n-router/issues/36
