### ISSUE TITLE
[5.3.0] bad release causing inability to unset `serverSetCookie`

### ISSUE THREAD

**Issue by QingqiShi** [i18nexus/next-i18n-router#53]
## Bug

When I set `serverSetCookie` to `never` the cookie is still being set by the server.

## Expected behavior

v5.3.0 release notes

> - Change default of serverSetCookie to "always".
> - Add "never" option to serverSetCookie. This is the same as undefined in previous versions.

Setting `serverSetCookie` to `never` should stop the server from setting cookie.

## Investigation

I can see that indeed the typings were updated to support the new `never` option https://unpkg.com/next-i18n-router@5.3.0/dist/types.d.ts

However, in `i18nRouter.js` line 97 (https://unpkg.com/next-i18n-router@5.3.0/dist/i18nRouter.js) it's still just checking for `if (serverSetCookie)` rather than `if (serverSetCookie !== 'never')`. However, this doesn't mean the behavior is unchanged, because on line 16 it's defaulting `serverSetCookie` to `'always'` which makes it basically impossible to unset when using the options defined in the typings.

This feel to me like a bad release that contained some old code, since the source code appears to be correct https://github.com/i18nexus/next-i18n-router/blob/main/src/i18nRouter.ts#L137

## Workaround

If anyone is facing this issue, you can workaround it like so:

```
export const i18nConfig: Config = {
  locales: ["en", "zh"],
  defaultLocale: "en",
  localeDetector: false,
  // @ts-expect-error https://github.com/i18nexus/next-i18n-router/issues/53
  serverSetCookie: null,
};
```

**Comment by QingqiShi** [comment]
Additionally, I should mention that this should have been a major version release since it contained a breaking change.

**Comment by i18nexus** [comment]
@QingqiShi Thank you so much for your investigation. You're absolutely right. It appears the TypeScript didn't compile prior to publishing v5.3.0. The compiled code is now published correctly in version 5.3.1. It was my understanding that the `"prepublish": "tsc"` in `package.json` should have ensured the release was compiled when running `npm publish`, but apparently that's not working. We will look into this.

**Comment by QingqiShi** [comment]
Appreciate the quick turnaround! Thank you.

**Comment by i18nexus** [comment]
You're right that this could have been a major version release since we're changing the default behavior of `serverSetCookie` from "never" to "always". But in the end we decided it's not necessarily a "breaking" change since nothing really breaks in this update. `serverSetCookie` can still be set to `undefined`. Hope this reasoning is makes sense.

We viewed this more as a feature update rather than a breaking change. We have had many support requests of developers trying to understand why they couldn't visit a non-default locale path. They didn't understand that they had to set a cookie to do that. It seems that `"always"` is the expected default behavior for most users.

**Comment by QingqiShi** [comment]
@i18nexus 

I think the problem with your `prepublish` is that it's not defined in the `scripts` object. https://github.com/i18nexus/next-i18n-router/blob/72a46bf90df53f653c148e168547c3acf5a8b5a3/package.json#L25 https://github.com/i18nexus/next-i18n-router/blob/72a46bf90df53f653c148e168547c3acf5a8b5a3/package.json#L21-L24 

And additionally, according to this https://github.com/npm/npm/issues/10074 it may be better to use the `prepublishOnly` script

**Comment by i18nexus** [comment]
@QingqiShi Ah, yep. That's it. Thanks!
