### ISSUE TITLE
Can we use this without pathname and just use cookie for locale recognition?

### ISSUE THREAD

**Issue by kneza23** [i18nexus/next-i18n-router#54]
I would be really thankful if you can help us regrading this. Thanks

**Comment by i18nexus** [comment]
This is not currently supported with this library. But I think we've had enough requests at this point to implement it 🙂

We'll use this issue to track progress of this. In the meantime, you can see an example implementation (without this library) in issue #2

**Comment by i18nexus** [comment]
This is now supported in v5.4.0 with the `noPrefix` config option 🎉
