### ISSUE TITLE
Typescript

### ISSUE THREAD

**Issue by enisze** [i18nexus/next-i18n-router#58]
Hey I am using react-i18next with the provided tutorial:
https://i18nexus.com/tutorials/nextjs/react-i18next 

I am just not able to configer the typescript part properly: 
```
import 'i18next'
import common from 'src/i18n/locales/de/common.json'
import errors from 'src/i18n/locales/de/errors.json'

export default resources

declare module 'i18next' {
	interface CustomTypeOptions {
		defaultNS: 'common'
		resources: {
			common: typeof common
			errors: typeof errors
		}
	}
}

```

I am able to use it for the defaultNS like t("somestring") 
But not for the errors namespace, I was hopeing to be able to use it like: t("errors:someErrorString") (client side)
Serverside i am using this:
```
export const getT = async () => {
	const locale = getLocale()

	const { t } = await initTranslations({
		locale,
	})

	return t
}
```

Which works great and also works with the above provided TS.
 I also tried creating a similar react-i18n.d.ts file but this did not work out

**Comment by i18nexus** [comment]
I'm going to close this and re-open your other issue since this issue is an extension of that. Better for other developers to see this conversation all in one place.
