### ISSUE TITLE
Thank you so, so much! ❤️❤️

### ISSUE THREAD

**Issue by amannn** [i18nexus/next-i18n-router#60]
Dear team from i18nexus,

I wasn't sure where the best place is to reach out, but I wanted to express my absolute gratitude for the sponsorship you've set up for `next-intl`!

I saw that you've published a tutorial on your website, that's so cool! If you have any questions or if you there's something `next-intl` can consider to work well with i18nexus, then please don't hesitate to reach out!

All the best,
Jan

**Comment by i18nexus** [comment]
Hi Jan, no problem! Thanks for all the work you do on `next-intl`. We see an increasing number of users using `next-intl` and we rarely get support requests about integrating with it thanks to your wonderful developer experience. 

Thanks for offering to consider feedback from us, but we'll stay out of your hair for now! Keep up the good work! 🙂

Best,
David
