### ISSUE TITLE
question: is there any way of using the t function without the hook usetranslation?

### ISSUE THREAD

**Issue by zakidze** [i18nexus/next-i18n-router#64]

**Comment by i18nexus** [comment]
Hi, can you let me know more about what you're trying to achieve?

**Comment by zakidze** [comment]
export const ProfileCompletionSchema = yup
  .object({
    Birthday: yup.date().required('Birthday is required'),
    Nationality: yup.string().required('Nationality is required'),
 
  })
  .required();
  
  
  this schema is in ts file  i m trying to internalisze the eror msg in this file

**Comment by i18nexus** [comment]
Right, useTranslation needs to be run in the context of a component. One thing you can do is:

```
import i18next from 'i18next'
...
i18next.t('Birthday is required')
```

But the problem with this is that you have to ensure that i18next is fully loaded before calling `t` this way. So this wouldn't work for your use case. This looks like more of a question for `yup` about how to dynamically render the error messages.

After a quick search, I found this: https://github.com/jquense/yup?tab=readme-ov-file#localization-and-i18n

This is the example they give:

```
import i18next from 'i18next';
import { setLocale } from 'yup';

setLocale({
  // use constant translation keys for messages without values
  mixed: {
    default: 'field_invalid',
  },
  // use functions to generate an error object that includes the value from the schema
  number: {
    min: ({ min }) => ({ key: 'field_too_short', values: { min } }),
    max: ({ max }) => ({ key: 'field_too_big', values: { max } }),
  },
});

// ...

let schema = yup.object().shape({
  name: yup.string(),
  age: yup.number().min(18),
});

try {
  await schema.validate({ name: 'jimmy', age: 11 });
} catch (err) {
  messages = err.errors.map((err) => i18next.t(err.key));
}
```

**Comment by zakidze** [comment]
thnks for your help  much appriciate it

**Comment by zakidze** [comment]
error={t(`${errors.Nationality?.message}`)}
 
 
 just this solved the issue
