### ISSUE TITLE
Catch errors in dynamic segment's [locale] error file

### ISSUE THREAD

**Issue by billypap1** [i18nexus/next-i18n-router#65]
I have followed the tutorial in order to integrate next-i18n-router to my NextJS v14.1.4 App, but I have an issue with the error file. 

The structure of my project: 
```
app
-[locale]
--test
--page.js
--error.js
-error.js
```

When the app receives an error, the error.js file never triggers. Is this a bug?  
I think the error.js doesn't trigger because of dynamic segment ([locale]).

**Comment by i18nexus** [comment]
I just tested in our example project with an `error.tsx` file inside of `[locale]` and it seems to work as expected.


My `error.tsx` file looks like this (copied from next.js docs):

```
'use client'
 
import { useEffect } from 'react'
 
export default function Error({
  error,
  reset,
}: {
  error: Error & { digest?: string }
  reset: () => void
}) {
  useEffect(() => {
    // Log the error to an error reporting service
    console.error(error)
  }, [error])
 
  return (
    <div>
      <h2>Something went wrong!</h2>
      <button
        onClick={
          // Attempt to recover by trying to re-render the segment
          () => reset()
        }
      >
        Try again
      </button>
    </div>
  )
}
```
