### ISSUE TITLE
localeDetector not applied when noPrefix is true

### ISSUE THREAD

**Issue by jschwindt** [i18nexus/next-i18n-router#70]
I'm not sure if it's a bug or a feature, but I'd expect that with `noPrefix: true` and in the absence of the language cookie,  if there is a valid language in the `Accept-Language` header the `i18nRouter` would set the language and the cookie accordingly.

Let me know it I'm right and I could send a PR with that.
Thanks!

**Comment by i18nexus** [comment]
You're absolutely right. That seems to have been an oversight. Right now it just returns the defaultLocale if no cookie present. We'll get started on a fix for this.

**Comment by i18nexus** [comment]
This is now fixed in version v5.4.2! Also added new tests for this case, all passing 🙂
