### ISSUE TITLE
next-i18n-router automatically changing the locale variable to a random locale variable sometimes

### ISSUE THREAD

**Issue by foadtkf** [i18nexus/next-i18n-router#72]
I have used three packages for implementing i18n on a website.
```
"next-i18n-router": "^5.4.0",
"i18next-resources-to-backend": "^1.2.0",
"react-i18next": "^14.1.0",
```
Here is my i18nConfig:
```
{
locales: locales,
defaultLocale: "en", 
prefixDefault: false, 
}
```
The problem is, the cookie variable "NEXT_LOCALE" changes automatically sometimes even if I try to access any route with the defaultLocale. Let's say I try to access mywebsite.com/products, for some unknown reasons, I will be redirected to mywebsite.com/de/products.

I've tried setting the value of the "NEXT_LOCALE" to "en" too but that din't work. I also created a client component that checks the cookie and if "NEXT_LOCALE" cookie does not exist, the component will set the cookie with value "en" which din't help either. How can I fix this issue?

**Comment by i18nexus** [comment]
When accessing `mywebsite.com/products`, there is no locale present in the pathname. When no locale is present, you will be redirected to the language present in your "NEXT_LOCALE" cookie. If no cookie is present, the `localeDetector` will be used to detect the visitor's preferred language from their request accept-language header. If you are being redirected to `mywebsite.com/de/products`, this likely means your browser language settings are set to use "de" and the `localeDetector` is detecting that.

If you've set "NEXT_LOCALE" to "en", you will be redirected from `mywebsite.com/products` to `mywebsite.com/en/products`. If you manually change the pathname to `mywebsite.com/de/products`, the middleware will automatically change your "NEXT_LOCALE" cookie from "en" to "de". If this is not the behavior you want, you may want to change the `serverSetCookie` config option to `'if-empty'`. You can read more about the `serverSetCookie` config option here: https://github.com/i18nexus/next-i18n-router?tab=readme-ov-file#serversetcookie-optional.

Let me know if this makes sense.

**Comment by foadtkf** [comment]
but I have set prefixDefault: false, and my default locale is 'en'. so, I can access the default localized path without specifying the locale variable, can't I?

**Comment by i18nexus** [comment]
This library treats it so that going to `mywebsite.com/products` is redirected based on cookie or header locale detection. The `prefixDefault` setting just makes it so when you're visiting the `/en` route, it is rewritten to just be `/`. 

If you're trying to have a link on your website that changes the page to use English, you can just have the link be `mywebsite.com/en/products`. The middleware will automatically set the cookie as "en" and then redirect to `mywebsite.com/products`. In other words, the middleware does not automatically set "en" as the cookie by simply visiting `mywebsite.com/products`.

**Comment by foadtkf** [comment]
I know that the middleware does not set "en" as the value of "NEXT_LOCALE" cookie variable by it's own and to handle that situation, I've created a client component that checks if there  exists a variable and if not found, it will set the value as "en". that's not the issue.


the issue is, let's say I've set the value as "en". Now, if I try to access another route let's say /route-1, instead of redirecting me to mywebsite.com/route-1, it sometimes(not always though but it keeps happening randomly) redirects me to mywebsite.com/de/route-1. That does not occur on localhost and only happens when I deploy my website.

**Comment by i18nexus** [comment]
> I've created a client component that checks if there exists a variable and if not found, it will set the value as "en"

I'm not sure I understand why you're doing this. This may be causing issues with your routing. The middleware already handles the automatic redirecting and does not expect you to handle it manually in a client component on app mount. If you're trying to avoid automatic locale detection, you should instead just set `localeDetector` to `false`.

**Comment by i18nexus** [comment]
Marking as stale. If you need more assistance, we're happy to continue helping in this thread.

**Comment by edossantos-sipcaller** [comment]
We're having the same issue of the web site randomly selecting a locale. We can see that the NEXT_LOCALE cookie is randomly changed, and then the next page request is shown in that language. But this happens without user intervention. It seems to be a bug when setting the NEXT_LOCALE cookie value somewhere.

**Comment by i18nexus** [comment]
Hi @edossantos-sipcaller. Can you describe exactly what's happening and share what your next-i18n-router config looks like?

**Comment by edossantos-sipcaller** [comment]
Hello @i18nexus, thanks for your answer.

We're running our web site on Vercel. The site is localized in 6 languages, and we provide a drop down menu to select the language from the browser. What we see is that while navigating the site, the NEXT_LOCALE cookie is randomly changed, without requesting the language change from the browser. This causes that you're navigating the site in English and all of a sudden it turns to Polish for example.

This is the configuration we have:
export const i18nConfig = {
	defaultLocale: "en",
	locales: ["en", "es", "fr", "it", "pl", "pt"]
} as const;

And our middleware is pretty simple:
export function middleware(request: NextRequest) {
    return i18nRouter(request, i18nConfig);
}


Now we fixed this by configuring:
serverSetCookie: 'if-empty'

And manually setting the cookie from the browser when the user selects a different language from the drop down menu.

But it looks like the invocation to i18nRouter(request, i18nConfig) is returning a new cookie with the default configuration.

**Comment by i18nexus** [comment]
@edossantos-sipcaller That's interesting. I'm glad that using `serverSetCookie: 'if-empty'` solves the problem.

Unfortunately we cannot debug the issue unless you can provide a reproducible example. If you get the time, it would be very helpful if you could reproduce using one the example projects in this repo so that we can see the issue.
