### ISSUE TITLE
localeDetector spamming warning

### ISSUE THREAD

**Issue by Kirill-Ponomarenko** [i18nexus/next-i18n-router#73]
I'm getting thousands of warnings in the logs:
```
Reverting to using defaultLocale: en
No valid locales in accept-language header: *
```
To my understanding it comes from here: https://github.com/i18nexus/next-i18n-router/blob/main/src/localeDetector.ts#L18C5-L18C78

But from user's perspective everything works fine. And I actually don't have so much visits. 
Is there a way to disable this warnings?

**Comment by Kirill-Ponomarenko** [comment]
Most likely some infrastructure calls, because our site blocked from the internet.

Thanks, will wait for this update!

**Comment by azimari-toure-ikbal** [comment]
I just came here for the exact same reason. Thanks for pointing that out

**Comment by Kirill-Ponomarenko** [comment]
I think it may be next/link prefetch. We have a lot of links on one page and it can generate 16 requests at a time

**Comment by i18nexus** [comment]
Console warning removed in v5.4.3 👍

**Comment by Kirill-Ponomarenko** [comment]
Appreciate how quickly you took care of it, thanks
