### ISSUE TITLE
[Need Help] Production root shows 404 while local works fine

### ISSUE THREAD

**Issue by LixingSun** [i18nexus/next-i18n-router#74]
I'm building [my nextjs project](https://github.com/LixingSun/oran-web) refer to this [given example](https://github.com/i18nexus/next-i18n-router/tree/main/examples/i18next-example).

The local environment totally works fine, where the `http://localhost:3000` shows in default "en" language as expected. `http://localhost:3000/en` and `http://localhost:3000/zh` also show different content properly.

But after deploying to [the production environment](https://oran.zone/) on Github Pages, the root url shows 404 page not found. But after manually changing the url to `https://oran.zone/en` or `https://oran.zone/zh` it can still show page properly.

I have checked that in config I have set `defaultLocale` to `en`, and local environment also proves it is working. I'm struggling on what is wrong with the production.

 I'm a bit new to latest next.js and these i18n libraries so hope can get some support. Appreciate a lot if can get any advice.

**Comment by i18nexus** [comment]
It looks like your site is not running the middleware. I don't know much about Github Pages, but I did find this library: https://github.com/gregrickaby/nextjs-github-pages

According to the README of the library, Github Pages does not support serverless or edge functions. This essentially means you are using a static export and using middleware is not supported.

**Comment by LixingSun** [comment]
Thanks for pointing this out. It does make sense. I'll try to find workaround without middleware or change other deployment solution.
