### ISSUE TITLE
Possibility to set cookie options

### ISSUE THREAD

**Issue by hugotiger** [i18nexus/next-i18n-router#75]
Really love the library! One issue we've hit though is that we need the ability to set the cookie domain. I can't find any option for setting any cookie options.

I'd suggest another field in the config file named something like `cookieOptions` where user land can pass cookie related options. I suggest the expiration date etc can be customized there as well. If you believe this would be a nice addition to the library and want help I can create a PR 😄

**Comment by i18nexus** [comment]
Hi there! Yeah this makes sense. Something I've thought about as well, but haven't had any requests for it. If you'd like to make a PR, we'd be happy to review.

**Comment by hugotiger** [comment]
Did a very rough implementation here: https://github.com/i18nexus/next-i18n-router/pull/77 Let me know if there's any changes needed etc. I couldn't really figure out how to test the response cookies since they're all undefined in the tests 🤔

**Comment by i18nexus** [comment]
Released in v5.5.0
