### ISSUE TITLE
Root path redirect adds trailing slash

### ISSUE THREAD

**Issue by hugotiger** [i18nexus/next-i18n-router#79]
Hi, thanks again for this amazing library!

I noticed that when accessing the root path, the i18n router language redirect adds a trailing slash. For example, visiting https://acme.com/ triggers a redirect to https://acme.com/en/. Since Next.js, by default, normalizes URLs by removing trailing slashes, this causes another redirect. While the issue is not critical and everything works fine for the end user, it could negatively impact SEO.

### Steps to Reproduce
Prerequisite: Either having `prefixDefault` or visiting with a language preference that will cause a redirect.
1. Access the root URL https://acme.com/
2. Observe the redirect to e.g. https://acme.com/en/.
3. Note the subsequent redirect caused by Next.js normalizing the URL.

### Expected Behavior
The URL should be normalized without causing an additional redirect.

### Actual Behavior
An additional redirect occurs due to the trailing slash added by the i18n router language redirect.

**Comment by i18nexus** [comment]
Interesting, we'll take a look at this and get back to you soon.

**Comment by i18nexus** [comment]
Fixed in version v5.5.1. Thanks for bringing to our attention!

**Comment by hugotiger** [comment]
> Fixed in version v5.5.1. Thanks for bringing to our attention!

Thanks for fixing 🙏
