### ISSUE TITLE
 [Bug] Changing Locale Without router.refresh() Causes useCurrentLocale to Return Incorrect Value

### ISSUE THREAD

**Issue by junseinagao** [i18nexus/next-i18n-router#80]
I found that `useCurrentLocale` returns the wrong value when changing routes without using `router.refresh()` in the client. For example, this happens when using the `<Link>` component.

I believe that `useCurrentLocale` is checking cookies before `usePathname`, which causes this behavior.

## Steps to Reproduce

I created a [codesandbox](https://codesandbox.io/p/github/junseinagao/next-i18n-router-use-current-locale-behavior/main?import=true&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clxj1hv3p00063b6k743ay7q6%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clxj1hv3p00023b6k9kgmwr9f%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clxj1hv3p00043b6knv615tx2%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clxj1hv3p00053b6kkhp7phyk%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clxj1hv3p00023b6k9kgmwr9f%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxj1hv3p00013b6k4hy8narm%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clxj1hv3p00023b6k9kgmwr9f%2522%252C%2522activeTabId%2522%253A%2522clxj1hv3p00013b6k4hy8narm%2522%257D%252C%2522clxj1hv3p00053b6kkhp7phyk%2522%253A%257B%2522id%2522%253A%2522clxj1hv3p00053b6kkhp7phyk%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clxj1jhtu00fk3b6kst6jfdkd%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252Fen%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clxj1jhtu00fk3b6kst6jfdkd%2522%257D%252C%2522clxj1hv3p00043b6knv615tx2%2522%253A%257B%2522id%2522%253A%2522clxj1hv3p00043b6knv615tx2%2522%252C%2522activeTabId%2522%253A%2522clxj1hvsh004r3b6kqv7ctdww%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxj1hv3p00033b6ko2aejm03%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clxj1hvjk001bcyg6gtbbb5kz%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clxj1hvsh004r3b6kqv7ctdww%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) example.

1. Open the CodeSandbox and open the preview in a new tab because CodeSandbox's preview in the editor doesn't use the browser's cookies.
2. Click the locale change links.
3. Observe that the values of `usePathname()` and `useCurrentLocale()` are different.

https://github.com/i18nexus/next-i18n-router/assets/54606780/71605cea-4aec-42bc-aadc-aba3e607e1cd

## Expected Behavior

useCurrentLocale should return the correct locale string when the route is changed by rendering caused by the client.

## Actual Behavior

useCurrentLocale returns a different value than the URL path after the route is changed by rendering caused by the client.

**Comment by i18nexus** [comment]
Hmm, good catch. Yes, `useCurrentLocale` is getting the locale from the cookie. But when it's a cached page, Next.js doesn't use the middleware, so the cookie is not updated.

We used to have it so that `useCurrentLocale` would simply get the locale by parsing the current pathname, but since we added the `noPrefix` option, we changed it to read the cookie instead.

The middleware not being called for cached pages is really out of our hands. If you're dependent on the server to set the cookie, using `router.refresh` on language change is required. That's why we included `router.refresh` in our `LanguageChanger` component in the example projects in this repo. We should certainly add this information to the README. 

If you don't call `router.refresh` after language change, there are other side effects besides the issue with `useCurrentLocale`. For example, in your video above, if you were to now click on a link like `/about-us`, you would receive the Japanese "about-us" page instead of the German "about-us" page. This is because your cookie is currently set to `ja`.

We will add to the documentation that `router.refresh` is required if changing language via user-clicked buttons or links.

A simple, global way to do this would probably be to have a client component in your root layout that has a `useEffect` that calls `router.refresh` any time the language changes. You would need to include a conditional in the `useEffect` that the previous language was not null since we don't want to refresh on initial app load.

**Comment by junseinagao** [comment]
@i18nexus 

> We will add to the documentation that router.refresh is required if changing language via user-clicked buttons or links.

That's a great idea. This information will help developers who use next-i18n-router.

---

I also found that `useCurrentLocale` works well if application never use the `NEXT_LANG` cookie. The `serverSetCookie: 'never'` setting is the key. This is a [example sandbox](https://codesandbox.io/p/github/junseinagao/next-i18n-router-use-current-locale-behavior/never-use-cookie?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clxl6u3rp000a3b6kgkanhci7%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clxl6u3rp00023b6khshebf34%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clxl6u3rp00083b6k89z7j0y5%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clxl6u3rp00093b6k86iuq01v%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clxl6u3rp00023b6khshebf34%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxl6u3ro00013b6kr5cri3zd%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%255D%252C%2522id%2522%253A%2522clxl6u3rp00023b6khshebf34%2522%252C%2522activeTabId%2522%253A%2522clxl6u3ro00013b6kr5cri3zd%2522%257D%252C%2522clxl6u3rp00093b6k86iuq01v%2522%253A%257B%2522id%2522%253A%2522clxl6u3rp00093b6k86iuq01v%2522%252C%2522activeTabId%2522%253A%2522clxl6ud87002a3b6kbdwk73x2%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clxl6ud87002a3b6kbdwk73x2%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252Fja%2522%257D%255D%257D%252C%2522clxl6u3rp00083b6k89z7j0y5%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxl6u3rp00033b6kq33cefot%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522clxl6u3rp00043b6k4qwp5ev7%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clxj1hvjk001bcyg6gtbbb5kz%2522%257D%252C%257B%2522id%2522%253A%2522clxl6u3rp00053b6kynvl13n6%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clxj1ll4d001rcyg6c0dl6vsp%2522%257D%252C%257B%2522id%2522%253A%2522clxl6u3rp00063b6kf8d9vzg3%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clxj1mz2s0021cyg6elb21ola%2522%257D%252C%257B%2522id%2522%253A%2522clxl6u3rp00073b6ka4snjtjw%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clxj2b8uw002jcyg62vs7czmh%2522%257D%255D%252C%2522id%2522%253A%2522clxl6u3rp00083b6k89z7j0y5%2522%252C%2522activeTabId%2522%253A%2522clxl6u3rp00033b6kq33cefot%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D).

How about also adding this information to the README and the comment of the useCurrentLocale method?
I guess some developers would like to use next-i18n-router's client hook without `router.refresh()` or without concerns about the behavior of `NEXT_LANG` cookie.

**Comment by i18nexus** [comment]
Using `serverSetCookie: "never"` will still have the same problems. The only difference is that `useCurrentLocale` will work correctly since the hook pulls the locale from the pathname when no cookie available. But you will still run into issues on cached pages as I described above.

**Comment by i18nexus** [comment]
Added to the documentation in the FAQ section
