### ISSUE TITLE
【Bug】the language does not switch when changing the defaultLocal

### ISSUE THREAD

**Issue by piesuke** [i18nexus/next-i18n-router#81]
It might be an issue with react-i18next, so if that is the case, I will raise an issue with react-i18next.

## Steps to Reproduce
I created a [codeSandbox example](https://codesandbox.io/p/github/piesuke/i8next-test/main?layout=%257B%2522sidebarPanel%2522%253A%2522GIT%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clxlmo3s000063b6l6fbn7oz9%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clxlmo3s000023b6lzy506rpn%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clxlmo3s000043b6lapj93p9v%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clxlmsmij00ek3b6lv8wwweby%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clxlmo3s000023b6lzy506rpn%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxlmo3s000013b6lkohvaujd%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clxlmo3s000023b6lzy506rpn%2522%252C%2522activeTabId%2522%253A%2522clxlmo3s000013b6lkohvaujd%2522%257D%252C%2522clxlmo3s000043b6lapj93p9v%2522%253A%257B%2522id%2522%253A%2522clxlmo3s000043b6lapj93p9v%2522%252C%2522activeTabId%2522%253A%2522clxlmo4wl004a3b6lqkt8h1r9%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxlmo3s000033b6lynarcnos%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clxlmo48s0016dletbyowf3c4%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clxlmo4wl004a3b6lqkt8h1r9%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clxlmsmij00ek3b6lv8wwweby%2522%253A%257B%2522id%2522%253A%2522clxlmsmij00ek3b6lv8wwweby%2522%252C%2522activeTabId%2522%253A%2522clxlmtihn00ki3b6lmtrc4u4c%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clxlmtihn00ki3b6lmtrc4u4c%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252Fen%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D).

1. Tap "en" on the Link type or Button type to switch to English.
2. Then, try to switch back to Japanese by pressing "ja", but the text does not change to Japanese. This issue is resolved by reloading the page.

https://github.com/i18nexus/next-i18n-router/assets/30724683/ab7fccb8-b524-4641-b4c1-c8f490871702

## Expected Behavior
When switching from English to Japanese (the default language), the switch operates correctly.

## Actual Behavior

When switching from English to Japanese (the default language), the switch operates incorrectly.

**Comment by i18nexus** [comment]
It looks like you have quite a custom i18next setup and several console errors. I highly recommend using our example i18next project to setup your project: https://github.com/i18nexus/next-i18n-router/tree/main/examples/i18next-example

**Comment by piesuke** [comment]
Implementing according to the example resolved the issue. Thank you!
