### ISSUE TITLE
Query parameters are removed when switching languages

### ISSUE THREAD

**Issue by Sathyaraj-dev** [i18nexus/next-i18n-router#83]
**Description:**
I'm experiencing an issue in my Next.js application where switching languages removes query parameters from the URL.

**Steps to Reproduce:**

1. Navigate to a page with query parameters, e.g., http://localhost:3000/ar/product?id=195&cat=187.
2. Switch the language using the language switcher component.
3. Observe the URL change. For example, it changes to http://localhost:3000/product and query parameters are removed.

**Expected Behavior:**

When switching languages, the query parameters should be preserved in the URL. For example, switching from http://localhost:3000/ar/product?id=195&cat=187 to the English version should result in http://localhost:3000/en/product?id=195&cat=187

Please tell me the solution for this issue.

Thanks,

**Comment by i18nexus** [comment]
Can you show your language switcher component please? You are probably not appending the query params when re-routing.

**Comment by Sathyaraj-dev** [comment]
`'use client';
import { useRouter } from 'next/navigation';
import { usePathname } from 'next/navigation';
import { useCurrentLocale } from "next-i18n-router/client";
import i18nConfig from '../i18Config';

export default function SelectLanguage() {
    const router = useRouter();
    const currentPathname = usePathname();
    const currentLocale = useCurrentLocale(i18nConfig);

  const handleChange = (e) => {
    const newLocale = e.target.value;
   // console.log(newLocale)

    // set cookie for next-i18n-router
    const days = 30;
    const date = new Date();
    date.setTime(date.getTime() + days * 24 * 60 * 60 * 1000);
    const expires = "; expires=" + date.toUTCString();
    document.cookie = `NEXT_LOCALE=${newLocale};expires=${expires};path=/`;

    // redirect to the new locale path
    if (
        currentLocale === i18nConfig.defaultLocale &&
        !i18nConfig.prefixDefault
      ) {
        router.push("/" + newLocale + currentPathname);
      } else {
        router.push(
          currentPathname.replace(`/${currentLocale}`, `/${newLocale}`)
        );
      }
      router.refresh();
  };
  return (
    <select onChange={handleChange} value={currentLocale}>
      <option value="en">English</option>
      <option value="ar">Arabic</option>
    </select>
  );
}
`
This is my LanguageSwitcher component. Please check and let me know.

Thanks,
Sathyaraj

**Comment by Sathyaraj-dev** [comment]
This code resolved that query parameter issue

`const queryString = searchParams.toString();
        const newPathname = currentLocale === i18nConfig.defaultLocale && !i18nConfig.prefixDefault 
            ? `/${newLocale}${currentPathname}`
            : currentPathname.replace(`/${currentLocale}`, `/${newLocale}`);
        
        const newUrl = queryString ? `${newPathname}?${queryString}` : newPathname;
        router.push(newUrl);
        router.refresh();`

Thanks,
Sathyaraj

**Comment by i18nexus** [comment]
Thanks for sharing!
