### ISSUE TITLE
Setting Language Header for Fetch API Based on Language Selection in Next.js

### ISSUE THREAD

**Issue by Sathyaraj-dev** [i18nexus/next-i18n-router#86]
Hi everyone,

I'm currently working on a Next.js project where I need to set the Accept-Language header for the Fetch API based on the user's language selection. I'm looking for guidance on how to achieve this in either middleware or next.config.js.

Here's the scenario:

1.The application supports multiple languages.
2.The user can select their preferred language.
3.I need to ensure that all fetch requests include the appropriate Accept-Language header according to the user's selection.

Has anyone implemented this before, or can someone point me in the right direction? Any help or examples would be greatly appreciated!

Thanks in advance!
Sathyaraj

**Comment by i18nexus** [comment]
Hi there! Setting request headers became a feature in Next 13. You can see an example in their docs here: https://nextjs.org/docs/app/building-your-application/routing/middleware#setting-headers

**Comment by Sathyaraj-dev** [comment]
Thank you for the information.
