### ISSUE TITLE
Default locale redirects to localhost after deployment

### ISSUE THREAD

**Issue by ICame4You** [i18nexus/next-i18n-router#88]
First of all I want to thank you for the the amazing job you do to help others use i18n in their projects!

I recenly cloned your [i18next-example](https://github.com/i18nexus/next-i18n-router/tree/main/examples/i18next-example) and locally it works totally fine. Without any changes I tried to deploy it. 

So I built the project:
`npm run build`

Then I wanted to start it on 127.0.0.1:
`npx next start -H 127.0.0.1 -p 3000`

And when I go to http://127.0.0.1:3000 it redirects me to http://localhost:3000/. Moreover in the network tab I see a lot of 307 temporary redirects. When I started to debug the middleware I found that it looks like it's just looping between http://localhost:3000/ and http://localhost:3000/en

![image](https://github.com/user-attachments/assets/2eb4a2af-622d-44ff-8c77-8088c55e8a51)

And if I open http://127.0.0.1:3000/de at first everything looks fine and working, but in the Network tab I see requests to localhost as well

![image](https://github.com/user-attachments/assets/2a7d65ec-26c7-4f63-9239-44f2ed527ce5)
![image](https://github.com/user-attachments/assets/b423e9bf-2328-4fc0-b487-544acbdf1c87)

Moreover I tried using ngrok and it also tries redirecting to localhost
`ngrok http 127.0.0.1:3000`

![image](https://github.com/user-attachments/assets/6a1b742b-d028-4238-aff0-e1f9cc62497a)

Could you please tell me if I miss something or do something wrong or is it a bug or anything? I have already tried many different approaches inside middleware to check for location, hostname from headers and netxUrl, even adding query parameters. All of it is either not working, or working not always good and looks like a total crutch

**Comment by harryy2510** [comment]
+1
Having the same issue for a while. Trying to figure out whats wrong there.

**Comment by i18nexus** [comment]
It seems to unfortunately be a quirk of NextJS. Whether it's a bug or intentional, I'm not sure. This issue was opened a year ago: https://github.com/vercel/next.js/issues/48230

The problem is that the request object that Next passes into the middleware has a `url` property of `localhost:3000` for some reason. I'm not sure if NextJS transforms the request this way, or perhaps it comes in that way from the client. It is an issue specifically with redirects in middleware. I'm not sure there is anything we can do on our end to solve this.

We'll continue investigating. If anyone else has any thoughts or ideas, please leave feedback here.

**Comment by harryy2510** [comment]
Same thougsht there after investigating throughly. Rewrites fail to work due to domain change. I tried building a small middleware, no facy things. A simple rewrite, and a custom domain. and it just fails.

**Comment by ICame4You** [comment]
By now we've found a solution by using this flag `skipMiddlewareUrlNormalize: true` in the next.config.js. It looks like it disables URL normalization in Next. There is a small advanced section in the [documentation](https://nextjs.org/docs/pages/building-your-application/routing/middleware#advanced-middleware-flags) about it

**Comment by i18nexus** [comment]
Thanks @ICame4You
