### ISSUE TITLE
Trans component serverside?

### ISSUE THREAD

**Issue by RebeccaStevens** [i18nexus/next-i18n-router#89]
Is it possible to use the [`Trans` component from `react-i18next`](https://react.i18next.com/latest/trans-component) for server-side translations?

```tsx
import { I18nextProvider, Trans } from "react-i18next";

// ...

<Trans
  i18nKey="myKey"
  components={{ italic: <i />, bold: <strong /> }}
/>
```

It currently throws with:

```sh
 ⨯ TypeError: (0 , react__WEBPACK_IMPORTED_MODULE_0__.createContext) is not a function
```

**Comment by i18nexus** [comment]
This seems to be the proper way to go about it: 
https://stackoverflow.com/a/78273131
