### ISSUE TITLE
Issue with Pages Transitioning from Static to SSG after Implementing i18next Package

### ISSUE THREAD

**Issue by Sathyaraj-dev** [i18nexus/next-i18n-router#91]
Before implementing the **i18next, react-i18next, i18next-resources-to-backend, and next-i18n-router packages**, all my pages were being prerendered as static content. However, after incorporating these packages, all the pages are now rendered as SSG (using getStaticProps), and they are not being cached.

Is there a solution to maintain static rendering and caching while using these packages? Any advice or guidance would be greatly appreciated.

Thanks,

**Comment by i18nexus** [comment]
For best performance using next-i18n-router, it is recommended to use `generateStaticParams` with your supported locales as seen in our example: https://github.com/i18nexus/next-i18n-router/blob/main/examples/i18next-example/app/%5Blocale%5D/layout.tsx#L15

**Comment by Sathyaraj-dev** [comment]
I am already using generateStaticParams, but all the pages are still coming through as dynamic. Please see the screenshot below for reference.

<img width="359" alt="image" src="https://github.com/user-attachments/assets/a7aa824f-efdb-4a9f-8cf4-19b69f59492d">

Could you please check if there are any issues in the code? Any help would be greatly appreciated.

Thanks.

**Comment by i18nexus** [comment]
Can you try running our example project and seeing if it works for you as expected?
https://github.com/i18nexus/next-i18n-router/tree/main/examples/i18next-example

**Comment by Sathyaraj-dev** [comment]
Thanks for the clarification. It's working fine now. The issue was on my side due to adding a timestamp in the fetch API. I appreciate the quick response!

Thanks again.
