### ISSUE TITLE
example repo: i want an example repo on how to use cookie options ,,,,  i love the new feature but how to use it

### ISSUE THREAD

**Issue by zakidze** [i18nexus/next-i18n-router#92]
would love to see example repo on the new functionality that appare on the site  
and the same goes for every new feature

**Comment by i18nexus** [comment]
The `cookieOptions` option wouldn't require a whole repo to give an example. It's a pretty straightforward option that allows you to customize the cookie attributes that are applied to the cookie on the `NextResponse`. A full list of attributes can be read here: https://nextjs.org/docs/app/api-reference/functions/cookies#options

A use case may look like this:

```
const i18nConfig: Config = {
  locales: ['en', 'de'],
  defaultLocale: 'en',
  cookieOptions: {
    path: '/',
    domain: 'example.com',
    secure: true,
    httpOnly: true,
    sameSite: 'strict',
    maxAge: 31536000
  }
};
```

**Comment by zakidze** [comment]
so i suppose this is for locale cookie is iy posible to set cookie on
responde

set anathor cookies

**Comment by i18nexus** [comment]
You can set your own cookies on the response. That would be done outside of next-i18n-router. Your implementation would look something like this:

```js
export function middleware(request: NextRequest) {
  const response = i18nRouter(request, i18nConfig);
  
  response.cookies.set('my-cookie', 'hello', { path: '/', domain: 'example.com' });
  
  return response;
}
```

**Comment by zakidze** [comment]
thank you soo much exactly what i wanted
