### ISSUE TITLE
Use i18nRouter middleware with others chained middlewares

### ISSUE THREAD

**Issue by vijote** [i18nexus/next-i18n-router#96]
Hi there, hope you're doing well.

I want to use the i18nRouter middleware alongside other middlewares, I'm expecting other middlewares to appear, for example an Auth middleware. I'd like to use a builder pattern and assign this middleware to the middlewares array, but I can't find how to do it since this middleware always returns a NextResponse.

This is what I'd like to use:
```
class MiddlewareBuilder {
  constructor() {
    this.middlewares = [];
  }

  use(middleware) {
    this.middlewares.push(middleware);
    return this;
  }

  async run(request) {
    for (const middleware of this.middlewares) {
      const response = await middleware(request);
      if (response) {
        return response;
      }
    }
    return NextResponse.next();
  }
}
```

Any idea how this could be achieved?

Thanks in advance!

**Comment by i18nexus** [comment]
Hi there. I'm not too sure that this method is going to work. Are you using NextAuth? You may want to take a look at issue #84 which shows an example.

**Comment by vijote** [comment]
I don't yet know how my authentication process is gonna be, probably not with that library.

For now I have changed my code to run this middleware at the end:
```
class MiddlewareBuilder {
   ...

    useFinal(middleware: MiddlewareFunction) {
        this.finalMiddleware = middleware;
        return this;
    }

    async run(request: NextRequest) {
       // run previous middlewares

        if (this.finalMiddleware) {
            return await this.finalMiddleware(request);
        }

        return NextResponse.next();
    }
}
```

**Comment by i18nexus** [comment]
Got it. If that works, then great!
