### ISSUE TITLE
Translate metadata

### ISSUE THREAD

**Issue by alejosky** [i18nexus/next-i18n-router#97]
Hi!

in your example [i18next-example-nextjs-15](https://github.com/i18nexus/next-i18n-router/tree/main/examples/i18next-example-nextjs-15), how is it possible to translate the [metadata](https://github.com/i18nexus/next-i18n-router/blob/86463a9e725878714ecc78388005639f35283e0c/examples/i18next-example-nextjs-15/app/%5Blocale%5D/layout.tsx#L11)?

**Comment by i18nexus** [comment]
Good question!

This should do it:

```js
export async function generateMetadata({params: {locale}}) {
  const { t } = await initTranslations(locale, namespaces);
 
  return {
    title: t('title'),
    description: t('description')
  };
}
```
